/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ClienteController;
import Model.Cliente;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author michael
 */
public class GuiBuscarClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiBuscarClientes
     */
    public GuiBuscarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_BuscaGeral = new javax.swing.JLabel();
        jp_Tabela = new javax.swing.JScrollPane();
        tabela_Cliente = new javax.swing.JTable();
        jb_Limpar = new javax.swing.JButton();
        jb_Buscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Busca de Clientes");

        jl_BuscaGeral.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_BuscaGeral.setText("Busca Geral de Clientes");

        tabela_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Cliente", "Nome", "CPF", "RG", "Celular", "Endereço", "Cidade", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jp_Tabela.setViewportView(tabela_Cliente);

        jb_Limpar.setText("Limpar");
        jb_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_LimparActionPerformed(evt);
            }
        });

        jb_Buscar.setText("Buscar");
        jb_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_Tabela, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_BuscaGeral)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jb_Limpar)
                .addGap(128, 128, 128)
                .addComponent(jb_Buscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_BuscaGeral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_Tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jb_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jb_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_LimparActionPerformed
        limpar();
    }//GEN-LAST:event_jb_LimparActionPerformed

    private void jb_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_BuscarActionPerformed
        try {
            buscaClientes();
        } catch (Exception ex) {
            Logger.getLogger(GuiBuscarClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_BuscarActionPerformed
    private void limpar(){
        DefaultTableModel dtm = (DefaultTableModel) tabela_Cliente.getModel();
        dtm.setNumRows(0);
    }
    private void buscaClientes() throws Exception{
    try{
        DefaultTableModel dtm = (DefaultTableModel) tabela_Cliente.getModel();
        String[] colun = new String [3];
        
        ClienteController cc = new ClienteController();
        ArrayList<Cliente> cb = new ArrayList<Cliente>();
        cb = cc.buscarTodosClientes();
        dtm.setNumRows(0);
        
        for(int i = 0; i <cb.size() ;i++){
            colun[0] = Integer.toString(cb.get(i).getIdCliente());
            colun[1] = cb.get(i).getNome();
            colun[2] = cb.get(i).getCpf();
            colun[3] = cb.get(i).getRg();
            colun[4] = cb.get(i).getCelular();
            colun[5] = cb.get(i).getEndereco();
            colun[6] = cb.get(i).getCidade();
            colun[4] = cb.get(i).getEstado();
            
            dtm.addRow(colun);
        }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(
        null,
                "Erro: "+ex.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_Buscar;
    private javax.swing.JButton jb_Limpar;
    private javax.swing.JLabel jl_BuscaGeral;
    private javax.swing.JScrollPane jp_Tabela;
    private javax.swing.JTable tabela_Cliente;
    // End of variables declaration//GEN-END:variables
}
