/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProdutoController;
import Model.Produto;
import javax.swing.JOptionPane;

/**
 *
 * @author michael
 */
public class GuiCadastroProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiCadastroProduto
     */
    public GuiCadastroProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void cadastrar(){
       try{
        Produto p = new Produto();
        p.setNomeProduto(jtf_Nome.getText());
        p.setMarca(jtf_Marca.getText());
        p.setCor(jtf_Cor.getText());
        p.setModelo(jtf_Modelo.getText());
        p.setValor(Double.parseDouble(jtf_Valor.getText()));
        
        ProdutoController pc = new ProdutoController();
        pc.cadastrarProduto(p);
       }catch(Exception ex) {
           JOptionPane.showMessageDialog(
           null,
                   "O Seguinte erro ocorreu: "+ex.getMessage());
       }
    }
    private void limpar(){
        jtf_Nome.setText("");
        jtf_Marca.setText("");
        jtf_Cor.setText("");
        jtf_Modelo.setText("");
        jtf_Valor.setText("");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Produto = new javax.swing.JLabel();
        jl_Marca = new javax.swing.JLabel();
        jl_Cor = new javax.swing.JLabel();
        jl_Modelo = new javax.swing.JLabel();
        jl_Valor = new javax.swing.JLabel();
        jtf_Nome = new javax.swing.JTextField();
        jtf_Marca = new javax.swing.JTextField();
        jtf_Cor = new javax.swing.JTextField();
        jtf_Modelo = new javax.swing.JTextField();
        jtf_Valor = new javax.swing.JTextField();
        jb_Limpar = new javax.swing.JButton();
        jb_Cadastrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jl_Produto.setText("Produto:");

        jl_Marca.setText("Marca:");

        jl_Cor.setText("Cor:");

        jl_Modelo.setText("Modelo:");

        jl_Valor.setText("Valor R$:");

        jb_Limpar.setText("Limpar");
        jb_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_LimparActionPerformed(evt);
            }
        });

        jb_Cadastrar.setText("Cadastrar");
        jb_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_CadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_Valor)
                    .addComponent(jl_Modelo)
                    .addComponent(jl_Cor)
                    .addComponent(jl_Marca)
                    .addComponent(jl_Produto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jb_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(jb_Cadastrar))
                    .addComponent(jtf_Nome)
                    .addComponent(jtf_Marca)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtf_Valor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addComponent(jtf_Modelo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtf_Cor, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Produto)
                    .addComponent(jtf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Marca)
                    .addComponent(jtf_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Cor)
                    .addComponent(jtf_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Modelo)
                    .addComponent(jtf_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Valor)
                    .addComponent(jtf_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_Cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jb_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_LimparActionPerformed
            limpar();
    }//GEN-LAST:event_jb_LimparActionPerformed

    private void jb_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_CadastrarActionPerformed
            cadastrar();
    }//GEN-LAST:event_jb_CadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_Cadastrar;
    private javax.swing.JButton jb_Limpar;
    private javax.swing.JLabel jl_Cor;
    private javax.swing.JLabel jl_Marca;
    private javax.swing.JLabel jl_Modelo;
    private javax.swing.JLabel jl_Produto;
    private javax.swing.JLabel jl_Valor;
    private javax.swing.JTextField jtf_Cor;
    private javax.swing.JTextField jtf_Marca;
    private javax.swing.JTextField jtf_Modelo;
    private javax.swing.JTextField jtf_Nome;
    private javax.swing.JTextField jtf_Valor;
    // End of variables declaration//GEN-END:variables
}
