/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProdutoController;
import Model.Produto;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author michael
 */
public class GuiDeletarProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiDeletarProduto
     */
    public GuiDeletarProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void deletar() throws Exception{
        
        Produto p = new Produto();
        ProdutoController pc = new ProdutoController();
        
        p.setIdProduto(Integer.parseInt(jtf_CodProduto.getText()));
        pc.deletarProdutoId(p);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_CodProduto = new javax.swing.JLabel();
        jb_Deletar = new javax.swing.JButton();
        jtf_CodProduto = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Deletar Produto");

        jl_CodProduto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jl_CodProduto.setText("Código do Produto:");

        jb_Deletar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jb_Deletar.setText("Deletar");
        jb_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_DeletarActionPerformed(evt);
            }
        });

        jtf_CodProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jl_CodProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_CodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jb_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_CodProduto)
                    .addComponent(jtf_CodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jb_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_DeletarActionPerformed
        try {
            deletar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
            null,
                    "O seguinte erro ocorreu: " +ex.getMessage());
        }
    }//GEN-LAST:event_jb_DeletarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_Deletar;
    private javax.swing.JLabel jl_CodProduto;
    private javax.swing.JTextField jtf_CodProduto;
    // End of variables declaration//GEN-END:variables
}
